# Generated by Django 3.1.7 on 2021-03-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yocalshops', '0002_auto_20210308_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.AddField(
            model_name='customer',
            name='helper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yocalshops.helper'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shoppingstreet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yocalshops.shoppingstreet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On the way to the store', 'On the way to the store'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yocalshops.customer'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
