# Generated by Django 3.1.7 on 2021-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yocalshops', '0003_auto_20210309_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The way', 'On The Way')], max_length=200, null=True),
        ),
    ]
