# Generated by Django 3.1.7 on 2021-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yocalshops', '0004_auto_20210312_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='address',
        ),
        migrations.AddField(
            model_name='helper',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='helper',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
